### ISSUE TITLE
Adding README for DSA with proper links to the existing DSA code.

### ISSUE THREAD

**Issue by ishwarrimal** [ishwarrimal/frontend-interview-preps#12]
Adding README for DSA with proper links to the existing DSA code.

**Comment by Abhii-07** [comment]
Can you assign to me as I already have a topic to add to the DSA folder which is Binary Search. @ishwarrimal

**Comment by ishwarrimal** [comment]
For adding a new topic, I request you to create a separate PR.
1 for updating the Readme, 1 for adding binary serach

**Comment by Abhii-07** [comment]
Sure, I will create 2 PR's
