### ISSUE TITLE
Add names and profile link of existing contributors to this repo.

### ISSUE THREAD

**Issue by ishwarrimal** [ishwarrimal/frontend-interview-preps#21]
Add names and profile link of contributors to this repo.

At the bottom of the main readme, we need to add the names and link of the contributors of this repo.

**Comment by someoneme** [comment]
I can pick this up

**Comment by someoneme** [comment]
I can pick this up

**Comment by someoneme** [comment]
https://github.com/ishwarrimal/frontend-interview-preps/pull/24 Please review

**Comment by ishwarrimal** [comment]
Issue closed
