### ISSUE TITLE
implement Linked List using JavaScript

### ISSUE THREAD

**Issue by ishwarrimal** [ishwarrimal/frontend-interview-preps#23]
implement Linked List using JavaScript

Write a JS code to implement LinkedList.

**Comment by ShikhaaT44** [comment]
I am interested in working on this issue, can I be assigned?

**Comment by AlexiusTatius** [comment]
Please can you assign me this issue?

**Comment by ishwarrimal** [comment]
Looks like @AlexiusTatius has already submitted the solution. Assigning it to @AlexiusTatius 
LMK if you want me to assign you a new issue @ShikhaaT44

**Comment by AlexiusTatius** [comment]
@ishwarrimal I have solved the issue. Would it take some time to decide whether my pull request be merged or not?

**Comment by ShikhaaT44** [comment]
> Looks like @AlexiusTatius has already submitted the solution. Assigning it to @AlexiusTatius LMK if you want me to assign you a new issue @ShikhaaT44

No issues. I'll check out other issues then

**Comment by AlexiusTatius** [comment]
@ishwarrimal Sir any updates?
