### ISSUE TITLE
Add more DSA questions

### ISSUE THREAD

**Issue by HarshitSharma4** [ishwarrimal/frontend-interview-preps#32]
I want to add more DSA questions.assign this issue to me in hacktoberfest

**Comment by AlexiusTatius** [comment]
please can you assign me this issue?

**Comment by ishwarrimal** [comment]
@AlexiusTatius this issue was created by @HarshitSharma4 so it'll be assigned to him.

**Comment by ishwarrimal** [comment]
@HarshitSharma4 please mention which DSA topic are you going to write about.

**Comment by ishwarrimal** [comment]
The issuer did not respond.
